apiVersion: v2
name: ibm-dpservice-instance
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "10.0-cd"
dependencies:
  - name: ibm-dpservice-instance
    version: 1.0.0
    repository: https://therayy.github.io/operators-instances/
